In [116]:
import pandas as pd
import numpy as np

## 📍 Loading Dataset

In [117]:
jobs = pd.read_csv("Dataset/job_descriptions.csv")
jobs.sample(5)

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
850259,2156411575602371,0 to 14 Years,B.Tech,$61K-$101K,Saint George's,Grenada,12.116500,-61.679000,Part-Time,66423,...,272-223-7326,Data Analyst,Data Scientist,Indeed,Data Scientists use their expertise in data an...,"{'Casual Dress Code, Social and Recreational A...",Machine learning algorithms and libraries (e.g...,Apply machine learning algorithms and statisti...,Berry Global Group,"{""Sector"":""Packaging"",""Industry"":""Packaging, C..."
962221,1779639542134207,3 to 13 Years,MCA,$64K-$123K,Pristina,Kosovo,42.602600,20.903000,Intern,49078,...,2919787057,Project Coordinator,Project Manager,Idealist,"Project Managers plan, execute, and oversee pr...","{'Childcare Assistance, Paid Time Off (PTO), R...",Project planning and scheduling Budget managem...,"Assist in project planning, execution, and mon...",Brewin Dolphin,"{""Sector"":""Financial Services"",""Industry"":""Fin..."
743162,894063024228431,3 to 12 Years,BBA,$61K-$110K,AsunciÃ³n,Paraguay,-23.442503,-58.443832,Contract,68247,...,(747)516-1304x091,Procurement Specialist,Procurement Manager,Snagajob,Procurement Managers oversee procurement proce...,"{'Employee Referral Programs, Financial Counse...",Procurement strategies Supplier management Neg...,"Manage procurement processes, vendor relations...",Barclays,"{""Sector"":""Financial Services"",""Industry"":""Ban..."
45382,1565162667865278,4 to 10 Years,MBA,$62K-$127K,Porto-Novo,Benin,9.307700,2.315800,Part-Time,114353,...,+1-362-561-9697x3761,Purchasing Agent,Inventory Manager,FlexJobs,An Inventory Manager oversees inventory levels...,"{'Employee Referral Programs, Financial Counse...",Inventory control Demand forecasting Supply ch...,"Manage inventory levels, track stock, and opti...",Unilever,"{""Sector"":""Consumer Goods"",""Industry"":""Consume..."
1082486,2974711796604267,1 to 14 Years,B.Com,$64K-$119K,Ljubljana,Slovenia,46.151200,14.995500,Temporary,123519,...,341.790.5677,Customer Service Manager,Customer Support Manager,Idealist,Customer Support Managers oversee a team of cu...,"{'Childcare Assistance, Paid Time Off (PTO), R...",Customer support Team leadership Customer sati...,"Oversee the customer support team, including h...",Beacon Roofing Supply,"{""Sector"":""Building Materials & Equipment"",""In..."

## 📍 Shape of data

In [118]:
jobs.shape

(1615940, 23)

## 📍 Info about Data

In [119]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615940 entries, 0 to 1615939
Data columns (total 23 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Job Id            1615940 non-null  int64
 1   Experience        1615940 non-null  object
 2   Qualifications    1615940 non-null  object
 3   Salary Range      1615940 non-null  object
 4   location          1615940 non-null  object
 5   Country           1615940 non-null  object
 6   latitude          1615940 non-null  float64
 7   longitude         1615940 non-null  float64
 8   Work Type         1615940 non-null  object
 9   Company Size      1615940 non-null  int64
 10  Job Posting Date  1615940 non-null  object
 11  Preference        1615940 non-null  object
 12  Contact Person    1615940 non-null  object
 13  Contact           1615940 non-null  object
 14  Job Title         1615940 non-null  object
 15  Role              1615940 non-null  object
 16  Job Portal        1615940 non-null  object
 17  Job Description   1615940 non-null  object
 18  Benefits          1615940 non-null  object
 19  skills            1615940 non-null  object
 20  Responsibilities  1615940 non-null  object
 21  Company           1615940 non-null  object
 22  Company Profile   1610462 non-null  object
dtypes: float64(2), int64(2), object(19)
memory usage: 283.6+ MB

## ⚠ Splitting Dataset 
* We should split data becauce we have a lot of Job Descriptions 
* we will split data to 2 Datasets
* first one for **Companies** and Second one for **Jobs**

In [120]:
jobs.columns

Index(['Job Id', 'Experience', 'Qualifications', 'Salary Range', 'location',
       'Country', 'latitude', 'longitude', 'Work Type', 'Company Size',
       'Job Posting Date', 'Preference', 'Contact Person', 'Contact',
       'Job Title', 'Role', 'Job Portal', 'Job Description', 'Benefits',
       'skills', 'Responsibilities', 'Company', 'Company Profile'],
      dtype='object')

## ✅ Here we Maked **Companies** Dataset

In [121]:
CompanyColumns = ["Job Id",'Company', 'Company Profile',"Company Size","location","Country", 'latitude', 'longitude','Contact Person', 'Contact']
companies = jobs.loc[:,CompanyColumns]
companies.to_csv("Dataset/Companies.csv",index=False)

## 🟢 Now we will make **Jobs** Dataset

In [122]:
columns = [column for column in jobs.columns.to_list() if column not in CompanyColumns]
columns.append("Job Id")

## 📍 Here we dropped any column in **Companies** Dataset

In [123]:
jobs = jobs.loc[:,columns]

## 🟢 Converting **`Job Posting Date`** to Datetme Format

In [124]:
new_column = pd.to_datetime(jobs["Job Posting Date"],format="%Y-%m-%d")

In [125]:
jobs["Date"] = new_column

In [126]:
jobs.drop(columns=["Job Posting Date"],inplace=True)
jobs.head()

,Experience,Qualifications,Salary Range,Work Type,Preference,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Job Id,Date
0,5 to 15 Years,M.Tech,$59K-$99K,Intern,Female,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",1089843540111562,2022-04-24
1,2 to 12 Years,BCA,$56K-$116K,Intern,Female,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",398454096642776,2022-12-19
2,0 to 12 Years,PhD,$61K-$104K,Temporary,Male,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,481640072963533,2022-09-14
3,4 to 11 Years,PhD,$65K-$91K,Full-Time,Female,Network Engineer,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",688192671473044,2023-02-25
4,1 to 12 Years,MBA,$64K-$87K,Intern,Female,Event Manager,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,117057806156508,2022-10-11

In [130]:
np.unique(jobs["Job Title"])

array(['Account Director', 'Account Executive', 'Account Manager',
       'Accountant', 'Administrative Assistant', 'Aerospace Engineer',
       'Architect', 'Architectural Designer', 'Art Director',
       'Art Teacher', 'Back-End Developer', 'Brand Ambassador',
       'Brand Manager', 'Business Analyst',
       'Business Development Manager', 'Chemical Analyst',
       'Chemical Engineer', 'Civil Engineer', 'Content Writer',
       'Copywriter', 'Customer Service Manager',
       'Customer Service Representative', 'Customer Success Manager',
       'Customer Support Specialist', 'Data Analyst', 'Data Engineer',
       'Data Entry Clerk', 'Data Scientist', 'Database Administrator',
       'Database Developer', 'Dental Hygienist',
       'Digital Marketing Specialist', 'Electrical Designer',
       'Electrical Engineer', 'Email Marketing Specialist',
       'Environmental Consultant', 'Environmental Engineer',
       'Event Coordinator', 'Event Manager', 'Event Planner',
       'Executive Assistant', 'Family Lawyer',
       'Family Nurse Practitioner', 'Finance Manager',
       'Financial Advisor', 'Financial Analyst', 'Financial Controller',
       'Financial Planner', 'Front-End Developer', 'Front-End Engineer',
       'Graphic Designer', 'HR Coordinator', 'HR Generalist',
       'HR Manager', 'Human Resources Manager', 'IT Administrator',
       'IT Manager', 'IT Support Specialist', 'Interior Designer',
       'Inventory Analyst', 'Investment Advisor', 'Investment Analyst',
       'Investment Banker', 'Java Developer', 'Key Account Manager',
       'Landscape Architect', 'Landscape Designer', 'Legal Advisor',
       'Legal Assistant', 'Legal Counsel', 'Legal Secretary',
       'Litigation Attorney', 'Market Analyst', 'Market Research Analyst',
       'Marketing Analyst', 'Marketing Coordinator', 'Marketing Director',
       'Marketing Manager', 'Marketing Specialist', 'Mechanical Designer',
       'Mechanical Engineer', 'Network Administrator', 'Network Analyst',
       'Network Engineer', 'Network Security Specialist',
       'Network Technician', 'Nurse Manager', 'Nurse Practitioner',
       'Occupational Therapist', 'Office Manager', 'Operations Manager',
       'Paralegal', 'Pediatrician', 'Personal Assistant',
       'Pharmaceutical Sales Representative', 'Physical Therapist',
       'Physician Assistant', 'Process Engineer',
       'Procurement Coordinator', 'Procurement Manager',
       'Procurement Specialist', 'Product Designer', 'Product Manager',
       'Project Coordinator', 'Project Manager', 'Psychologist',
       'Public Relations Specialist', 'Purchasing Agent', 'QA Analyst',
       'QA Engineer', 'Quality Assurance Analyst', 'Registered Nurse',
       'Research Analyst', 'Research Scientist', 'SEM Specialist',
       'SEO Analyst', 'SEO Specialist', 'Sales Associate',
       'Sales Consultant', 'Sales Manager', 'Sales Representative',
       'Social Media Coordinator', 'Social Media Manager',
       'Social Worker', 'Software Architect', 'Software Developer',
       'Software Engineer', 'Software Tester', 'Speech Therapist',
       'Structural Engineer', 'Substance Abuse Counselor',
       'Supply Chain Analyst', 'Supply Chain Manager',
       'Systems Administrator', 'Systems Analyst', 'Systems Engineer',
       'Tax Consultant', 'Teacher', 'Technical Writer', 'UI Developer',
       'UX Researcher', 'UX/UI Designer', 'Urban Planner', 'Veterinarian',
       'Web Designer', 'Web Developer', 'Wedding Planner'], dtype=object)

In [127]:
jobs.to_csv("Dataset/Jobs.csv",index=False)

---

<h1 align="center">✅ The End of Jobs Notebook</h1>


---